/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package appregistrodeusuario;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ale
 */
public class JDialog extends javax.swing.JDialog {

    /**
     * Creates new form JDialog
     */
    public JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Font f = new Font("Segoe UI", 0, 14);
        jFormattedTextFieldNacimiento.setFont(f);
        jFormattedTextFieldNumControl.setFont(f);
        jFormattedTextFieldTelefono.setFont(f);
        
        jLabelErrorCorreo.setVisible(false);
        jLabelErrorNacimiento.setVisible(false);
        jLabelErrorNumControl.setVisible(false);
        jLabelErrorTelefono.setVisible(false);
        jLabelErrorUsuario.setVisible(false);
        jLabelErrorContrasena.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonValidar = new javax.swing.JButton();
        jTextFieldCorreoElec = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jFormattedTextFieldTelefono = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldNacimiento = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNumControl = new javax.swing.JFormattedTextField();
        jToggleButtonMostrar = new javax.swing.JToggleButton();
        jProgressBar = new javax.swing.JProgressBar();
        jLabelErrorUsuario = new javax.swing.JLabel();
        jLabelErrorCorreo = new javax.swing.JLabel();
        jLabelErrorTelefono = new javax.swing.JLabel();
        jLabelErrorNumControl = new javax.swing.JLabel();
        jLabelErrorNacimiento = new javax.swing.JLabel();
        jLabelErrorContrasena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dialog Registro");
        setBackground(new java.awt.Color(250, 240, 230));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(53, 47, 68));
        jTextFieldUsuario.setToolTipText("Ingrese un nombre de usuario de minimo 5 y \nmaximo 13 caracteres\nPuede usar Letras (A-z), Numeros (0-9) y\nGuiones( _  - )");
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 47, 68));
        jLabel1.setText("Nombre de Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 47, 68));
        jLabel2.setText("Correo electronico:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 47, 68));
        jLabel3.setText("Constraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 47, 68));
        jLabel4.setText("Numero de telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 47, 68));
        jLabel5.setText("Registro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jButtonValidar.setBackground(new java.awt.Color(53, 47, 68));
        jButtonValidar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonValidar.setForeground(new java.awt.Color(185, 180, 199));
        jButtonValidar.setText("Enviar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 80, 30));

        jTextFieldCorreoElec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCorreoElec.setForeground(new java.awt.Color(53, 47, 68));
        jTextFieldCorreoElec.setToolTipText("Ingrese un correo electronico valido \n puede usar @gmail, @outlook, @hotmail, \n@jcarlos19.");
        jTextFieldCorreoElec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCorreoElecFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldCorreoElec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, -1));

        jPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(53, 47, 68));
        jPasswordField.setToolTipText("Ingrese una contraseña valida \nde entre 8 a 13 caracteres \nDebe contener Mayusculas, Minusculas, \nNumeros y Caracteres especiales. ");
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 180, -1));

        jFormattedTextFieldTelefono.setForeground(new java.awt.Color(53, 47, 68));
        try {
            jFormattedTextFieldTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("871#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefono.setToolTipText("Ingrese un numero de telefono valido \nDe Torreon, Gomez, Matamoros o Lerdo ");
        jFormattedTextFieldTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldTelefonoFocusLost(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 47, 68));
        jLabel6.setText("Fecha de  nacimiento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(53, 47, 68));
        jLabel7.setText("Numero de control:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jFormattedTextFieldNacimiento.setForeground(new java.awt.Color(53, 47, 68));
        try {
            jFormattedTextFieldNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNacimiento.setToolTipText("Ingresa tu fecha de nacimiento \ncon el formato DD/MM/AAAA \n(DD->Dia, MM->Mes, AAAA->Año)");
        jFormattedTextFieldNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldNacimientoFocusLost(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 180, 30));

        jFormattedTextFieldNumControl.setForeground(new java.awt.Color(53, 47, 68));
        try {
            jFormattedTextFieldNumControl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##13####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNumControl.setToolTipText("Ingresa tu numero de control \ndel Instituto Tecnologico de La Laguna");
        jFormattedTextFieldNumControl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldNumControlFocusLost(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, -1));

        jToggleButtonMostrar.setBackground(new java.awt.Color(53, 47, 68));
        jToggleButtonMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButtonMostrar.setForeground(new java.awt.Color(185, 180, 199));
        jToggleButtonMostrar.setText("Mostrar");
        jToggleButtonMostrar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonMostrarStateChanged(evt);
            }
        });
        getContentPane().add(jToggleButtonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 120, 30));

        jProgressBar.setForeground(new java.awt.Color(92, 84, 112));
        getContentPane().add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 540, 10));

        jLabelErrorUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErrorUsuario.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorUsuario.setText("*");
        getContentPane().add(jLabelErrorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabelErrorCorreo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErrorCorreo.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorCorreo.setText("*");
        getContentPane().add(jLabelErrorCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabelErrorTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErrorTelefono.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorTelefono.setText("*");
        getContentPane().add(jLabelErrorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jLabelErrorNumControl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErrorNumControl.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorNumControl.setText("*");
        getContentPane().add(jLabelErrorNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabelErrorNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErrorNacimiento.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorNacimiento.setText("*");
        getContentPane().add(jLabelErrorNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabelErrorContrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelErrorContrasena.setForeground(new java.awt.Color(254, 0, 0));
        jLabelErrorContrasena.setText("*");
        getContentPane().add(jLabelErrorContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        // TODO add your handling code here:
        if(ExpresionRegularValidar.validarUsario(jTextFieldUsuario.getText())){
            jTextFieldUsuario.setForeground(Color.BLACK);
            jLabelErrorUsuario.setVisible(false);
        }
        else{
            jTextFieldUsuario.setForeground(Color.RED);
            jLabelErrorUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jTextFieldCorreoElecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCorreoElecFocusLost
        // TODO add your handling code here:
        if(ExpresionRegularValidar.validarCorreo(jTextFieldCorreoElec.getText())){
            jTextFieldCorreoElec.setForeground(Color.BLACK);
            jLabelErrorCorreo.setVisible(false);
        }
        else{
            jTextFieldCorreoElec.setForeground(Color.RED);
            jLabelErrorCorreo.setVisible(true);
        }
    }//GEN-LAST:event_jTextFieldCorreoElecFocusLost

    private void jFormattedTextFieldTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefonoFocusLost
        // TODO add your handling code here:
        if(ExpresionRegularValidar.validarTel(jFormattedTextFieldTelefono.getText())){
            jFormattedTextFieldTelefono.setForeground(Color.BLACK);
            jLabelErrorTelefono.setVisible(false);
        }
        else{            
            jFormattedTextFieldTelefono.setForeground(Color.RED);
            jLabelErrorTelefono.setVisible(true);
        }
    }//GEN-LAST:event_jFormattedTextFieldTelefonoFocusLost

    private void jFormattedTextFieldNumControlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNumControlFocusLost
        // TODO add your handling code here:
        if(ExpresionRegularValidar.validarNumControl(jFormattedTextFieldNumControl.getText())){
            jFormattedTextFieldNumControl.setForeground(Color.BLACK);
            jLabelErrorNumControl.setVisible(false);
        }
        else{
            jFormattedTextFieldNumControl.setForeground(Color.RED);
            jLabelErrorNumControl.setVisible(true);

        }
    }//GEN-LAST:event_jFormattedTextFieldNumControlFocusLost

    private void jFormattedTextFieldNacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNacimientoFocusLost
        // TODO add your handling code here:
        if(ExpresionRegularValidar.validarNacimiento(jFormattedTextFieldNacimiento.getText())){
            jFormattedTextFieldNacimiento.setForeground(Color.BLACK);
            jLabelErrorNacimiento.setVisible(false);

        }
        else{
            jFormattedTextFieldNacimiento.setForeground(Color.RED);
            jLabelErrorNacimiento.setVisible(true);
        }
    }//GEN-LAST:event_jFormattedTextFieldNacimientoFocusLost

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        // TODO add your handling code here:
        String pass = new String(jPasswordField.getPassword());
        if(ExpresionRegularValidar.validarContrasena(pass)){
            jPasswordField.setForeground(Color.BLACK);
            jLabelErrorContrasena.setVisible(false);
        }
        else{
            jPasswordField.setForeground(Color.RED);
            jLabelErrorContrasena.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jToggleButtonMostrarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonMostrarStateChanged
        // TODO add your handling code here:
        
        if(jToggleButtonMostrar.isSelected()){
            jToggleButtonMostrar.setText("No mostrar");
            jPasswordField.setEchoChar((char) 0);
        }
        else{
            jToggleButtonMostrar.setText("Mostrar");
            jPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_jToggleButtonMostrarStateChanged

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:
        
        String pass = new String(jPasswordField.getPassword());
        
        if(ExpresionRegularValidar.validarUsario(jTextFieldUsuario.getText()) && 
           ExpresionRegularValidar.validarCorreo(jTextFieldCorreoElec.getText()) &&
           ExpresionRegularValidar.validarTel(jFormattedTextFieldTelefono.getText()) &&
           ExpresionRegularValidar.validarNumControl(jFormattedTextFieldNumControl.getText()) &&
           ExpresionRegularValidar.validarNacimiento(jFormattedTextFieldNacimiento.getText()) &&
           ExpresionRegularValidar.validarContrasena(pass))
                JOptionPane.showMessageDialog(this,"Usuario creado con exito","Exito",1);
        else{
            jTextFieldCorreoElec.requestFocus();
            jTextFieldUsuario.requestFocus();
            jFormattedTextFieldNacimiento.requestFocus();
            jFormattedTextFieldNumControl.requestFocus();
            jFormattedTextFieldTelefono.requestFocus();
            jPasswordField.requestFocus();
            JOptionPane.showMessageDialog(this,"Revisa los parametros en rojo y con *","Error",0);
        }
          
    }//GEN-LAST:event_jButtonValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog dialog = new JDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JFormattedTextField jFormattedTextFieldNacimiento;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumControl;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelErrorContrasena;
    private javax.swing.JLabel jLabelErrorCorreo;
    private javax.swing.JLabel jLabelErrorNacimiento;
    private javax.swing.JLabel jLabelErrorNumControl;
    private javax.swing.JLabel jLabelErrorTelefono;
    private javax.swing.JLabel jLabelErrorUsuario;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JTextField jTextFieldCorreoElec;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JToggleButton jToggleButtonMostrar;
    // End of variables declaration//GEN-END:variables
}
